session12 -リファクタリング
r0ar-69/ios-training pull request #1
Opened 2021-07-28 07:57 UTC by r0ar-69

# 修正内容
- テストパスするように修正
- エラーが起きた時にアラートが表示されないバグを修正
- 対応できないエラーを対応できるように修正
- タイポの修正

2021-07-29 20:40 UTC, ykws requested changes
バグ修正＝リファクタリングではないです。

1つのコミットに複数の修正が混ざっているので、分けて欲しいです。

最低4つのバグについて以下のような問い立てで説明が欲しいです。

- どういう状態だった
- 何が原因だった
- どう改善した

2021-07-30 02:09 UTC, r0ar-69 commented
@ykws リファクタリングと不具合修正をイコールとして考えていました。ありがとうございます。
コミット粒度もPR出してから気づいて、今回の課題の反省点だと考えていました。
今後のsession12の進め方としてはどのようにしていくべきでしょうか？

2021-07-30 03:07 UTC, ykws commented
@r0ar-69 コミットし直してもらうのが良いと思います。

もし、今の修正で万全だと考えるなら、
一度 `git reset --soft HEAD^` して staging に戻して、必要な差分を段階的に残して他は restore してコミットし直しても良いですが、
多分やり直した方が楽かなと思います。

2021-07-30 03:09 UTC, r0ar-69 commented
@ykws ありがとうございます。先程史さんとミーティングしていて、同じ回答をいただいたのでそうしようと思います。

2021-07-30 05:39 UTC, r0ar-69 commented
新しくPR出し直すため、このPRをCloseします

2021-07-30 05:39 UTC, closed without merging